apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-add-namespace-cm
spec:
  rules:
    - name: generate-add-namespace-cm
      match: 
        resources:
          kinds:
            - Namespace
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: default-configmap
        namespace: "{{request.object.metadata.name}}"
        data:
          data:
            key1: "Giropops"
            key2: "Strigus"
