apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-shiriu
  name: nginx-shiriu
spec:
  containers:
  - image: nginx
    name: nginx-shiriu
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
